src/accounts/urls.py
from django.urls import path, re_path

from . import views
from .views import (
    CustomLoginView,
    CutomeSignupView,
    CustomConfirmEmailView,
    CustomPasswordChangeView,
    CustomPasswordResetView,
    CustomEmailView,
    CustomPasswordResetDoneView,
    CustomPasswordResetFromKeyView
)

app_name = "accounts"

urlpatterns = [
    path('', CustomLoginView.as_view(), name='account_login'),

    path('login/', CustomLoginView.as_view(), name='account_login'),

    path('logout/', views.logout_user, name='logout'),

    path("password/change/", CustomPasswordChangeView.as_view(),
         name="account_change_password"),
    # path("password/set/", views.password_set, name="account_set_password"),
    # path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", CustomEmailView.as_view(), name="account_email"),
    path("confirm-email/", views.confirm_email_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$",
            CustomConfirmEmailView.as_view(), name="account_confirm_email"),

    # password reset
    path("password/reset/", CustomPasswordResetView.as_view(),
         name="account_reset_password"),

    path("password/reset/done/", CustomPasswordResetDoneView.as_view(),
         name="account_reset_password_done"),

    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            CustomPasswordResetFromKeyView.as_view(),
            name="account_reset_password_from_key"),

    # path("password/reset/key/done/", views.password_reset_from_key_done,
    #     name="account_reset_password_from_key_done"),

    path('signup/', CutomeSignupView.as_view(), name='account_signup'),

]

src/appcenter/urls.py
from django.urls import path

from . import views

app_name = "app"

urlpatterns = [
    path('', views.appcenter, name='appcenter'),
]

src/landing/urls.py
from django.urls import path

from . import views

app_name = "landing"

urlpatterns = [
    path('', views.get_landing_page, name='index'),
]

src/pf_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('landing.urls'), name="landing:index"),
    path('admin/', admin.site.urls),
    path('app/', include('appcenter.urls'), name='app:appcenter'),
    path("accounts/", include('accounts.urls'), name="accounts:account_login"),
    path('accounts/', include('allauth.urls')),
    path(r'accounts/profile/', include('profiles.urls'), name="profile:profile"),


]


handler404 = 'landing.views.page_not_found_404'

src/appcenter/models.py
from django.db import models

"""AppCenter model controls all models that relates to the app
Other app related models reports to it.
"""

"""
class AppCenter(models.Model):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             related_name="appcenter",
                             null=True)
"""


# Create your models here.
class Category(models.Model):
    ASSETS = 'ASSETS'
    EXPENSES = 'EXPENSES'
    INCOMES = 'INCOMES'
    LIABILITIES = 'LIABILITIES'

    CATEGORY_CHOICES = [
        (ASSETS, 'Assets'),
        (EXPENSES, 'Expenses'),
        (INCOMES, 'Incomes'),
        (LIABILITIES, 'Liabilities'),
    ]
    account_category = models.CharField(
        max_length=12,
        choices=CATEGORY_CHOICES,
        default=ASSETS,
    )


class Asset(models.Model):
    asset_name = models.CharField(max_length=10)
    asset_description = models.CharField(max_length=50)
    asset_currency = models.CharField(max_length=10)
    asset_type = models.CharField(max_length=10)
    asset_initial_balance = models.DecimalField(max_digits=19,
                                                decimal_places=2)
    asset_current_balance = models.DecimalField(max_digits=19,
                                                decimal_places=2)
    asset_open_date = models.DateField('opening date')


class AssetType(models.Model):
    CASH = 'CASH'
    BANK = 'BANK'
    STOCK = 'STOCK'
    ASSET = 'ASSET'

    CATEGORY_CHOICES = [
        (CASH, 'Cash'),
        (BANK, 'Bank'),
        (STOCK, 'Stock'),
        (ASSET, 'Asset'),
    ]
    account_category = models.CharField(
        max_length=6,
        choices=CATEGORY_CHOICES,
        default=BANK,
    )


class Liability(models.Model):
    liability_name = models.CharField(max_length=10)
    liability_description = models.CharField(max_length=50)
    liability_currency = models.CharField(max_length=10)
    liability_type = models.CharField(max_length=10)
    liability_initial_balance = models.DecimalField(max_digits=19,
                                                    decimal_places=2)
    liability_current_balance = models.DecimalField(max_digits=19,
                                                    decimal_places=2)
    liability_open_date = models.DateField('opening date')


class Stock(models.Model):
    stock_name = models.CharField(max_length=15)
    stock_description = models.CharField(max_length=50)
    stock_currency = models.CharField(max_length=10)
    stock_security = models.CharField(max_length=10)
    stock_initial_balance = models.DecimalField(max_digits=19,
                                                decimal_places=2)
    stock_current_balance = models.DecimalField(max_digits=19,
                                                decimal_places=2)
    stock_open_date = models.DateField('opening date')
    no_of_shares = models.DecimalField(max_digits=19, decimal_places=0)


class Income(models.Model):
    income_name = models.CharField(max_length=10)
    income_description = models.CharField(max_length=50)
    income_currency = models.CharField(max_length=10)
    income_current_balance = models.DecimalField(max_digits=19,
                                                 decimal_places=2)


class Expense(models.Model):
    expense_name = models.CharField(max_length=10)
    expense_description = models.CharField(max_length=50)
    expense_currency = models.CharField(max_length=10)
    expense_current_balance = models.DecimalField(max_digits=19,
                                                  decimal_places=2)


class Account(models.Model):
    account_category = models.ForeignKey(Category, on_delete=models.CASCADE)
    account_type = models.CharField(max_length=10)
    account_name = models.CharField(max_length=50)
    account_code = models.CharField(max_length=50)
    account_currency_security = models.CharField(max_length=10)
    account_initial_balance = models.DecimalField(max_digits=19,
                                                  decimal_places=2)
    account_current_balance = models.DecimalField(max_digits=19,
                                                  decimal_places=2)
    account_open_date = models.DateField('opening date')


class Transactions(models.Model):
    transfer_account = models.ForeignKey(Account, on_delete=models.CASCADE)
    transfer_date = models.DateTimeField('transaction date')
    transfer_description = models.CharField(max_length=50)
    transfer_target = models.CharField(max_length=20)
    transfer_cleared = models.BooleanField()
    transfer_deposit = models.DecimalField(max_digits=19, decimal_places=2)
    transfer_withdrawal = models.DecimalField(max_digits=19, decimal_places=2)
    transfer_balance = models.DecimalField(max_digits=19, decimal_places=2)
    transfer_conversion_rate = models.DecimalField(max_digits=19,
                                                   decimal_places=6)
    transfer_fee = models.DecimalField(max_digits=19, decimal_places=2)

src/appcenter/views.py
from django.shortcuts import render

# from django.urls import reverse_lazy
# from authtools import views as authviews
# from braces import views as bracesviews
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required

from assets.models import Asset

User = get_user_model()


@login_required
# Create your views here.
def appcenter(request):
    latest_asset_list = Asset.objects.order_by('-asset_type')

    context = {
        'latest_asset_list': latest_asset_list
    }
    return render(request, 'appcenter/appcenter.html', context)


def page_not_found_404(request, exception):
    return render(request, '404.html')

src/appcenter/templates/appcenter/_footer.html
<footer class="sticky-footer bg-white">
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>Copyright &copy; Webbased Accounting Software 2020</span>
        </div>
    </div>
</footer>

src/appcenter/templates/appcenter/_scripts.html
{% load static %}
<!-- Bootstrap core JavaScript-->
<script src="{% static 'sb-admin-2/vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'sb-admin-2/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Core plugin JavaScript-->
<script src="{% static 'sb-admin-2/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

<!-- Custom scripts for all pages-->
<script src="{% static 'sb-admin-2/js/sb-admin-2.min.js' %}"></script>

src/appcenter/templates/appcenter/_sidebar.html
{% block sidebar %}
        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'app:appcenter'%}">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-coins"></i>
                </div>
                <div class="sidebar-brand-text mx-3">Personal Finance Software <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Components</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" href="buttons.html">Buttons</a>
                        <a class="collapse-item" href="cards.html">Cards</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Utilities</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Utilities:</h6>
                        <a class="collapse-item" href="utilities-color.html">Colors</a>
                        <a class="collapse-item" href="utilities-border.html">Borders</a>
                        <a class="collapse-item" href="utilities-animation.html">Animations</a>
                        <a class="collapse-item" href="utilities-other.html">Other</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item active">
                <a class="nav-link" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
                    aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Pages</span>
                </a>
                <div id="collapsePages" class="collapse show" aria-labelledby="headingPages"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Login Screens:</h6>
                        <a class="collapse-item" href="login.html">Login</a>
                        <a class="collapse-item" href="register.html">Register</a>
                        <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                        <div class="collapse-divider"></div>
                        <h6 class="collapse-header">Other Pages:</h6>
                        <a class="collapse-item" href="404.html">404 Page</a>
                        <a class="collapse-item active" href="blank.html">Blank Page</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="charts.html">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->
        {% endblock sidebar %}

src/appcenter/templates/appcenter/_styles.html
{% load static %}
<link href="{% static 'sb-admin-2/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
<link
    href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
    rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{% static 'sb-admin-2/css/sb-admin-2.min.css' %}" rel="stylesheet">
<link href="{% static 'onepage/img/favicon.png' %}" rel="icon">

src/appcenter/templates/appcenter/_topbar.html
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 12, 2019</div>
                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 7, 2019</div>
                        $290.29 has been deposited into your account!
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-warning">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 2, 2019</div>
                        Spending Alert: We've noticed unusually high spending for your account.
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60"
                            alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                            problem I've been
                            having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60"
                            alt="">
                        <div class="status-indicator"></div>
                    </div>
                    <div>
                        <div class="text-truncate">I have the photos that you ordered last month, how
                            would you like them
                            sent to you?</div>
                        <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60"
                            alt="">
                        <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Last month's report looks great, I am very happy with
                            the progress so
                            far, keep up the good work!</div>
                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                            alt="">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                            told me that people
                            say this to all dogs, even if they aren't good...</div>
                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.email }}</span>
                <!--<img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">-->
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url 'profile:profile'%}">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'accounts:logout' %}" data-toggle="modal"
                    data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>

src/appcenter/templates/appcenter/appcenter.html
{% extends "appcenter/base.html" %}

src/appcenter/templates/appcenter/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta content="Web based personal finance software" name="descriptison">
    <meta content="" name="keywords">

    <title>{% block title %}{% include "_brandname.html" %} :: App Blank {% endblock %}</title>

    {% include "appcenter/_styles.html" %}
    {% block styles %}
    {%endblock styles%}
</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        {% block sidebar %}
            {% include "appcenter/_sidebar.html" %}
        {% endblock sidebar %}
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                {% include "appcenter/_topbar.html" %}
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                {% block content %}
                <div class="container-fluid">
                    <!-- Page Heading -->
                    <h1 class="h3 mb-4 text-gray-800">Blank Page</h1>
                    Welcome {{ user.email }}. This is a blank page that is going to be replaced.
                </div>
                {% endblock content %}
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            {% include "appcenter/_footer.html" %}
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="{% url 'accounts:logout' %}">Logout</a>
                </div>
            </div>
        </div>
    </div>

</body>


{% block scripts %}
{% include "appcenter/_scripts.html" %}
{% endblock scripts %}

</html>