src/accounts/urls.py
from django.urls import path, re_path

from . import views
from .views import (
    CustomLoginView,
    CutomeSignupView,
    CustomConfirmEmailView,
    CustomPasswordChangeView,
    CustomPasswordResetView,
    CustomEmailView,
    CustomPasswordResetDoneView,
    CustomPasswordResetFromKeyView
)

app_name = "accounts"

urlpatterns = [
    path('', CustomLoginView.as_view(), name='account_login'),

    path('login/', CustomLoginView.as_view(), name='account_login'),

    path('logout/', views.logout_user, name='logout'),

    path("password/change/", CustomPasswordChangeView.as_view(),
         name="account_change_password"),
    # path("password/set/", views.password_set, name="account_set_password"),
    # path("inactive/", views.account_inactive, name="account_inactive"),

    # E-mail
    path("email/", CustomEmailView.as_view(), name="account_email"),
    path("confirm-email/", views.confirm_email_sent,
         name="account_email_verification_sent"),
    re_path(r"^confirm-email/(?P<key>[-:\w]+)/$",
            CustomConfirmEmailView.as_view(), name="account_confirm_email"),

    # password reset
    path("password/reset/", CustomPasswordResetView.as_view(),
         name="account_reset_password"),

    path("password/reset/done/", CustomPasswordResetDoneView.as_view(),
         name="account_reset_password_done"),

    re_path(r"^password/reset/key/(?P<uidb36>[0-9A-Za-z]+)-(?P<key>.+)/$",
            CustomPasswordResetFromKeyView.as_view(),
            name="account_reset_password_from_key"),

    # path("password/reset/key/done/", views.password_reset_from_key_done,
    #     name="account_reset_password_from_key_done"),

    path('signup/', CutomeSignupView.as_view(), name='account_signup'),

]

src/landing/urls.py
from django.urls import path

from . import views

app_name = "landing"

urlpatterns = [
    path('', views.get_landing_page, name='index'),
]

src/pf_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('landing.urls'), name="landing:index"),
    path('admin/', admin.site.urls),
    path('app/', include('appcenter.urls'), name='app:appcenter'),
    path("accounts/", include('accounts.urls'), name="accounts:account_login"),
    path('accounts/', include('allauth.urls')),
    path(r'accounts/profile/', include('profiles.urls'), name="profile:profile"),


]


handler404 = 'landing.views.page_not_found_404'

src/registration/urls.py
from django.urls import path

from . import views
from .views import (
               RegistrationLogoutView,
               RegistrationPasswordResetView
               )

app_name = "registration"

urlpatterns = [
    path('', views.login_user, name='login'),

    path('login/', views.login_user, name='login'),
    path('logout/', RegistrationLogoutView.as_view(), name='logout'),

    path('password_change/', views.password_change, name='password_change'),
    path('password_change/done/',
         views.password_change_done,
         name='password_change_done'),

    path('password_reset/',
         RegistrationPasswordResetView.as_view(),
         name='password_reset'),

    path('password_reset/done/',
         views.password_reset_done,
         name='password_reset_done'),

    path('reset/', views.reset, name='reset'),
    path('reset/done/', views.reset_done, name='reset_done'),
    path('register/', views.register, name='register'),

]

src/accounts/forms.py
from django.contrib.auth.forms import (
    # AuthenticationForm,
    UserCreationForm,
    PasswordChangeForm,
    PasswordResetForm,
    SetPasswordForm)
from allauth.account.forms import LoginForm
from django import forms
from django.contrib.auth.models import User


class CustomLoginForm(LoginForm):
    """AuthenticationForm is hacked to using email as label.
    username is set to take email as input.
    """

    username = forms.CharField(widget=forms.TextInput(
        attrs={'placeholder': 'Enter Your Username...'}))

    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'placeholder': 'Enter Your Password...'}))

    remember_me = forms.BooleanField(required=False, initial=False)

    class Meta:
        model = User
        fields = [
            'username',
            'password',
            'remember_me',
        ]


class SignupForm(UserCreationForm):
    username = forms.CharField(
        min_length=4,
        label='Username',
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Your Username...'}))

    email = forms.EmailField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Your Email...'}))

    password1 = forms.CharField(
        min_length=4,
        label='Password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Enter Your Password...'}))

    password2 = forms.CharField(
        label='Repeat Password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repeat Your Password...'}))

    class Meta:
        model = User
        fields = ('username',
                  'email',
                  'password1',
                  'password2', )


# PasswordChangeForm
class CustomPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(
        label='Current Password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Enter Your Current Password...',
                'autofocus': 'autofocus'}))

    new_password1 = forms.CharField(
        label='New Password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Enter Your New Password...'}))

    new_password2 = forms.CharField(
        label='Repeat New Password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repeat Your New Password...'}))

    class Meta:
        model = User
        fields = ('old_password',
                  'new_password1',
                  'new_password2')


class CustomPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(
        max_length=50,
        required=True,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Enter Your Email...'}))

    class Meta:
        model = User
        fields = ('email')


class CustomSetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New Password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Enter Your New Password...'}))

    new_password2 = forms.CharField(
        label='Repeat New Password',
        widget=forms.PasswordInput(
            attrs={
                'placeholder': 'Repeat Your New Password...'}))

    class Meta:
        model = User
        fields = ('new_password1',
                  'new_password2')

src/accounts/views.py
from django.shortcuts import render, redirect

from django.contrib.auth import (
    update_session_auth_hash,
    login,
    logout,
    authenticate
)

from django.contrib.auth.decorators import login_required

from .forms import (
    CustomPasswordChangeForm
)

from allauth.account.forms import LoginForm
from allauth.account.views import (
    LoginView,
    SignupView,
    EmailView,
    ConfirmEmailView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordChangeView,
    PasswordResetFromKeyView,
)


def login_user(request):
    """Use function view to get better control over form.errors and
    remember_me checkbox.
    """
    login_form = LoginForm()

    if not request.user.is_authenticated:
        if request.method == "POST":
            login_form = LoginForm(data=request.POST)

            if login_form.is_valid():
                username = login_form.cleaned_data['login']
                password = login_form.cleaned_data['password']
                remember_me = login_form.cleaned_data.get("remember_me")

                user = authenticate(request,
                                    username=username,
                                    password=password)

                if not remember_me:
                    request.session.set_expiry(0)
                    request.session.modified = True

                if user is not None:
                    login(request, user)
                    # Redirect to a success page.
                    return redirect('app:appcenter')

    else:
        return redirect('app:appcenter')

    context = {
        "login_form": login_form
    }

    return render(request, "accounts/login.html", context)


class CustomLoginView(LoginView):
    template_name = "accounts/login.html"
    success_url = "/app/"


def logout_user(request):
    logout(request)
    return redirect('accounts:account_login')


class CutomeSignupView(SignupView):
    """Use custom template for the signup form.
    """
    template_name = 'accounts/signup.html'


class CustomEmailView(EmailView):
    template_name = 'accounts/email.html'


class CustomConfirmEmailView(ConfirmEmailView):
    """View for verifying new user account.
    This will show after the new user click the verification
    link in their email.
    """
    template_name = "accounts/email_confirm.html"


def confirm_email_sent(request):
    """Notifying the new user that an account verification email
    had been sent to their email addresses.
    """
    context = {}
    return render(request, "accounts/verification_email_sent.html", context)


class CustomPasswordResetDoneView(PasswordResetDoneView):
    template_name = "accounts/password_reset_done.html"


class CustomPasswordResetView(PasswordResetView):
    template_name = 'accounts/password_reset_confirm.html'


class CustomPasswordResetFromKeyView(PasswordResetFromKeyView):
    template_name = "accounts/password_reset_from_key.html"


class CustomPasswordChangeView(PasswordChangeView):
    template_name = "accounts/change-password.html"


@login_required
def password_change(request):
    password_change_form = CustomPasswordChangeForm()

    context = {
        "password_change_form": password_change_form
    }

    if request.method == 'POST':
        form = CustomPasswordChangeForm(user=request.user, data=request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
        else:
            context = {
                "password_change_form": password_change_form
            }
        return render(request, "accounts/change-password.html", context)

    return render(request, "accounts/change-password.html", context)


@login_required
def password_change_done(request):
    password_change_form = CustomPasswordChangeForm()

    context = {
        "password_change_form": password_change_form
    }

    if request.method == 'POST':
        return render(request, "accounts/change-password.html", context)

src/accounts/templates/accounts/_footer.html
{% load static %}
{% block footer %}
<footer class="sticky-footer">
    <div class="container my-auto">
        <div class="copyright text-center my-auto text-white">
            <span>Copyright &copy; Webbased Accounting Software 2020</span>
        </div>
    </div>
</footer>
{% endblock footer %}

src/accounts/templates/accounts/_header.html
{% load static %}
{% block header %}
<header class="header_area">
    <div class="main_menu">
        <div class="container box_1620">
          <!-- Brand and toggle get grouped for better mobile display -->
          <a class="navbar-brand logo_h" href="{% url 'accounts' %}"><img src="{% static 'site/img/pfas_logo.png' %}" alt=""></a>
        </div>
    </div>
  </header>
{% endblock header %}

src/accounts/templates/accounts/_navbar.html
{% load static %}
<header class="header_area">
    <div class="main_menu">
        <div class="container box_1620">
            <!-- Brand and toggle get grouped for better mobile display -->
            <a class="navbar-brand logo_h" href="{% url 'accounts:account_login' %}">
                <img src="{% static 'site/img/pfas_logo.png' %}" alt="">
            </a>
        </div>
    </div>
</header>

src/accounts/templates/accounts/_styles.html
{% load static %}
<!-- Custom fonts for this template-->
<link href="{% static 'sb-admin-2/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
<link
  href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
  rel="stylesheet">

<!-- Custom styles for this template-->
<link href="{% static 'sb-admin-2/css/sb-admin-2.min.css' %}" rel="stylesheet">

src/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
{% load crispy_forms_tags %}

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta content="Web based personal finance software" name="descriptison" />
    <meta content="" name="keywords" />

    <!-- Django's form.errors will use <ul>
        This CSS style removes ident and button of the <li> elements
    -->
    <style type="text/css">
        ul {
            padding: 0;
            list-style-type: none;
        }
    </style>
    <link href="{% static 'onepage/img/favicon.png' %}" rel="icon" />

    {% include "accounts/_styles.html" %}
    {% block styles %}
    {% endblock styles %}
    <title>
    {% include "_brandname.html" %} {% block title %} :: Base {% endblock %}
    </title>
</head>

<body class="bg-gradient-primary">
    {% block navbar %}
    {% include "accounts/_navbar.html"%}
    {% endblock navbar %}

    <div class="container">
        <!-- Outer Row -->
        <div class="row justify-content-center">
            <div class="col-xl-10 col-lg-12 col-md-9">
                {% block content %} Base block. {% endblock content %}
            </div>

            <!-- Footer -->
            {%include "accounts/_footer.html"%}
            <!-- End of Footer -->
        </div>
    </div>
    {%include "accounts/_scripts.html"%}
</body>

</html>

src/accounts/templates/accounts/change-password.html
{% extends "app_base.html" %}

src/accounts/templates/accounts/email.html
{% extends "accounts/base.html" %}

{% load i18n %}

{% block head_title %}{% trans "E-mail Addresses" %}{% endblock %}

{% block content %}
<h1>{% trans "E-mail Addresses" %}</h1>
{% if user.emailaddress_set.all %}
<p>{% trans 'The following e-mail addresses are associated with your account:' %}</p>

<form action="{% url 'account_email' %}" class="email_list" method="post">
  {% csrf_token %}
  <fieldset class="blockLabels">

    {% for emailaddress in user.emailaddress_set.all %}
    <div class="ctrlHolder">
      <label for="email_radio_{{forloop.counter}}" class="{% if emailaddress.primary %}primary_email{%endif%}">

        <input id="email_radio_{{forloop.counter}}" type="radio" name="email" {% if emailaddress.primary or user.emailaddress_set.count == 1 %}checked="checked" {%endif %} value="{{emailaddress.email}}" />

        {{ emailaddress.email }}
        {% if emailaddress.verified %}
        <span class="verified">{% trans "Verified" %}</span>
        {% else %}
        <span class="unverified">{% trans "Unverified" %}</span>
        {% endif %}
        {% if emailaddress.primary %}<span class="primary">{% trans "Primary" %}</span>{% endif %}
      </label>
    </div>
    {% endfor %}

    <div class="buttonHolder">
      <button class="secondaryAction" type="submit" name="action_primary">{% trans 'Make Primary' %}</button>
      <button class="secondaryAction" type="submit" name="action_send">{% trans 'Re-send Verification' %}</button>
      <button class="primaryAction" type="submit" name="action_remove">{% trans 'Remove' %}</button>
    </div>

  </fieldset>
</form>

{% else %}
<p><strong>{% trans 'Warning:'%}</strong> {% trans "You currently do not have any e-mail address set up. You should really add an e-mail address so you can receive notifications, reset your password, etc." %}</p>

{% endif %}


<h2>{% trans "Add E-mail Address" %}</h2>

<form method="post" action="{% url 'account_email' %}" class="add_email">
  {% csrf_token %}
  {{ form.as_p }}
  <button name="action_add" type="submit">{% trans "Add E-mail" %}</button>
</form>

{% endblock %}


{% block extra_body %}
<script type="text/javascript">
  (function() {
    var message = "{% trans 'Do you really want to remove the selected e-mail address?' %}";
    var actions = document.getElementsByName('action_remove');
    if (actions.length) {
      actions[0].addEventListener("click", function(e) {
        if (!confirm(message)) {
          e.preventDefault();
        }
      });
    }
  })();
</script>
{% endblock %}

src/accounts/templates/accounts/forgot-password.html
{% extends "accounts/base.html" %}

{% block title %}::Password Reset{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
      <div class="col-lg-6">
        <div class="p-5">
          <div class="text-center">
            <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
            <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you
              a link to
              reset your password!</p>
          </div>
          <form method='POST' class="user">
            {% csrf_token %}
            {{ form.email.errors|crispy }}
            {{ form|crispy }}
            <input class="btn btn-primary btn-user btn-block" type="submit" value="Reset my password" />
          </form>
          <hr>
          <div class="text-center">
            <a class="small" href="{% url 'accounts:account_signup' %}">Create an Account!</a>
          </div>
          <div class="text-center">
            <a class="small" href="{% url 'accounts:account_login' %}">Already have an account? Login!</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

src/accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block title %}:: Login{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card o-hidden border-0 shadow-lg my-5">
    <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
            <div class="col-lg-6">
                <div class="p-5">
                    <div class="text-center">
                        <h1 class="h4 text-gray-900 mb-4">Please Login</h1>
                    </div>
                    <form action="{% url 'accounts:account_login' %}" method='POST' class="user">
                        {% csrf_token %}

                        <div class="form-group">{{ form|crispy }}</div>

                        <input class="btn btn-primary btn-user btn-block" type="submit" value="Login" />

                        <hr>
                        <a href="index.html" class="btn btn-google btn-user btn-block">
                            <i class="fab fa-google fa-fw"></i> Login with Google
                        </a>
                        <a href="index.html" class="btn btn-facebook btn-user btn-block">
                            <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                        </a>
                    </form>
                    <hr>
                    <div class="text-center">
                        <a class="small" href="{% url 'accounts:account_reset_password' %}">Forgot Password?</a>
                    </div>
                    <div class="text-center">
                        <a class="small" href="{% url 'accounts:account_signup' %}">Create an Account!</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock content %}

src/accounts/templates/accounts/password_reset_confirm.html
{% extends "accounts/base.html" %}

{% block title %}::Password Reset Email Sent{% endblock %}
{% load crispy_forms_tags %}


{% block content %}
<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
      <div class="col-lg-6">
        <div class="p-5">
          <div class="text-center">
            <h1 class="h4 text-gray-900 mb-2">Password Reset</h1>
            <p class="mb-4">Please reset your password</p>
          </div>
          <form method='POST' class="user">
            {% csrf_token %}
            <div class="form-group">
              {{ form|crispy }}
            </div>
            <input class="btn btn-primary btn-user btn-block" type="submit" value="Reset Password" />

          </form>
          <div class="text-center">
            <a class="small" href="{% url 'accounts:account_signup' %}">Create an Account!</a>
          </div>
          <div class="text-center">
            <a class="small" href="{% url 'accounts:account_login' %}">Already have an account? Login!</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

src/accounts/templates/accounts/password_reset_email.html
{% load i18n %}
{% autoescape off %}
You're receiving this email because you requested a password reset for email {{ email }} at {{ site_name }}.

Please go to the following page and choose a new password: {{ protocol}}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token %}


"Thanks for using our site!

The {{ site_name }} team

{% endautoescape %}

src/accounts/templates/accounts/register.html
{% extends "accounts/login.html" %}
{% load crispy_forms_tags %}
{% block title %}:: Register{% endblock %}

{% block content %}
<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
      <div class="col-lg-7">
        <div class="p-5">
          <div class="text-center">
            <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
          </div>
          <form action="{% url 'accounts:register' %}" method='POST' class=" user">
            {% csrf_token %}
            <div class="form-group">
              {{ signup_form.email|as_crispy_field }}
            </div>
            <div class="form-group">
              {{ signup_form.password1|as_crispy_field }}
            </div>
            <div class="form-group">
              {{ signup_form.password2|as_crispy_field }}
            </div>
            <input class="btn btn-primary btn-user btn-block" type="submit" value="Register Account" />

            <hr>
            <a href="index.html" class="btn btn-google btn-user btn-block">
              <i class="fab fa-google fa-fw"></i> Register with Google
            </a>
            <a href="index.html" class="btn btn-facebook btn-user btn-block">
              <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
            </a>
          </form>
          <hr>
          <div class="text-center">
            <a class="small" href="{% url 'accounts:password_reset' %}">Forgot Password?</a>
          </div>
          <div class="text-center">
            <a class="small" href="{% url 'accounts:login' %}">Already have an account? Login!</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

src/accounts/templates/accounts/signup.html
{% extends "accounts/base.html" %}
{% load crispy_forms_tags %}
{% block title %}:: Register{% endblock %}

{% block content %}
<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
      <div class="col-lg-7">
        <div class="p-5">
          <div class="text-center">
            <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
          </div>
          <form method='POST' class=" user">
            {% csrf_token %}
            <div class="form-group">
              {{ form |crispy}}
            </div>
            <input class="btn btn-primary btn-user btn-block" type="submit" value="Register Account" />

            <hr>
            <a href="index.html" class="btn btn-google btn-user btn-block">
              <i class="fab fa-google fa-fw"></i> Register with Google
            </a>
            <a href="index.html" class="btn btn-facebook btn-user btn-block">
              <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
            </a>
          </form>
          <hr>
          <div class="text-center">
            <a class="small" href="{% url 'accounts:account_reset_password' %}">Forgot Password?</a>
          </div>
          <div class="text-center">
            <a class="small" href="{% url 'accounts:account_login' %}">Already have an account? Login!</a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}

src/accounts/templates/accounts/verification_email_sent.html
{% extends "accounts/base.html" %}

{% block title %} :: Verification Email Sent{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="card o-hidden border-0 shadow-lg my-5">
  <div class="card-body p-0">
    <!-- Nested Row within Card Body -->
    <div class="row">
      <div class="col-lg-6 d-none d-lg-block bg-register-image"></div>
      <div class="col-lg-6">
        <div class="p-5">
          <div class="text-center">
            <h1 class="h4 text-gray-900 mb-2">Verification Email Sent</h1>
            <p class="mb-4">We've sent you a verification email.</p>
          </div>

          <div class="text-center">
            <a href="{% url 'accounts:account_login' %}">
              Back to Login?
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
{% endblock content %}